apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "triggermesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "triggermesh.name" . }}
    helm.sh/chart: {{ include "triggermesh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  vhost.conf: |
    server {
      listen 8080;
      gzip on;
      # Angular CLI already has gzipped the assets (ng build --prod --aot)
      gzip_static  on;
      location /api {
        proxy_pass https://kubernetes.default.svc.cluster.local:443;
      }
      location / {
        root   /usr/share/nginx/html;
        try_files $uri /index.html;
      }
    }
    # Redirect www to non-www
    # Taken from https://easyengine.io/tutorials/nginx/www-non-www-redirection/
    server {
      server_name "~^www\.(.*)$" ;
      return 301 $scheme://$1$request_uri ;
    }
